version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: css-loader
    versions:
    - 5.0.0
    - 5.0.1
    - 5.0.2
    - 5.1.2
    - 5.2.0
  - dependency-name: workbox-window
    versions:
    - 6.0.2
    - 6.1.2
  - dependency-name: rollup
    versions:
    - 2.36.2
    - 2.39.0
    - 2.40.0
    - 2.41.2
  - dependency-name: workbox-build
    versions:
    - 6.0.2
    - 6.1.1
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: execa
    versions:
    - 4.0.3
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: jquery
    versions:
    - 3.5.1
